# This is the most complete version, Since the port is running within itself, there are no difference on the cluster ip, all of the ip should be pointing to itself.
version: '3'
services:
  lagom-with-seed:
    image: ${DB_HOST_IP}:5000/justice-league
    ports:
      - "9000:9000"
    environment:
      - DB_HOST_IP=192.168.1.244
      - BIND_IP=0.0.0.0
      - KAFKA_HOST_IP_AND_PORT=192.168.1.244:9092
      - CLUSTER_IP1=lagom-with-seed
      - CLUSTER_IP2=lagom-with-seed
      - HOST_IP=lagom-with-seed
      - HOST_PORT=2551
    networks:
      justicenetwork:
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
networks:
  justicenetwork:
